// <auto-generated />
using System;
using ActivityTracker.Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActivityTracker.Domain.Migrations
{
    [DbContext(typeof(ActivityTrackerDbContext))]
    partial class ActivityTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActivityTracker.Contract.Database.ActivityUser", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("activity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivityId"));

                    b.Property<DateTime>("ActivityDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_dateTime");

                    b.Property<int>("ActivityDuration")
                        .HasColumnType("integer")
                        .HasColumnName("activity_duration");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("activity_type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_activity", "public");
                });

            modelBuilder.Entity("ActivityTracker.Contract.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tbl_user", "public");
                });

            modelBuilder.Entity("ActivityTracker.Contract.Database.ActivityUser", b =>
                {
                    b.HasOne("ActivityTracker.Contract.Database.User", "User")
                        .WithMany("ActivityUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ActivityTracker.Contract.Database.User", b =>
                {
                    b.Navigation("ActivityUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
